export const AVAILABLE_GENRES = {
    'Action': 0,
    'Adventure': 0,
    'Animation': 0,
    'Biography': 0,
    'Comedy': 0,
    'Crime': 0,
    'Documentary': 0,
    'Drama': 0,
    'Family': 0,
    'Fantasy': 0,
    'Film-Noir': 0,
    'History': 0,
    'Horror': 0,
    'Music': 0,
    'Musical': 0,
    'Mystery': 0,
    'Romance': 0,
    'Sci-Fi': 0,
    'Sport': 0,
    'Thriller': 0,
    'War': 0,
    'Western': 0
};
